NightscoutShareServer/Controllers/GlucoseController.cs
using Newtonsoft.Json;
using NightscoutShareServer.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace NightscoutShareServer.Controllers
{
    public class GlucoseController : Controller
    {
        private bool CheckAuth(string sessionId)
        {
            //do any checks here to ensure users applicationid and sessionid is authenticated
            //currently there is no authentication needed to access this shareserver, so simply return true
            return true;
        }

        private string encodeGlucose(List<ShareGlucose> glucose)
        {
            var settings = new JsonSerializerSettings
            {
                DateFormatHandling = DateFormatHandling.MicrosoftDateFormat
            };

            return JsonConvert.SerializeObject(glucose, settings);
        }

        private List<ShareGlucose> mockupGlucoseValues()
        {
            //examples on generating fake data
            var glucose = new List<ShareGlucose>();
            var now = DateTime.Now;
            var threeminsago = now - TimeSpan.FromMinutes(3);
            glucose.Add(
                new ShareGlucose { DT = now, ST = now, WT = now.ToUniversalTime(), Trend = (ShareGlucoseSlopeOrdinals)4, Value = 166 }
            );

            glucose.Add(
                new ShareGlucose { DT = threeminsago , ST = threeminsago , WT = threeminsago.ToUniversalTime(), Trend = ShareGlucoseSlopeOrdinals.UP_45, Value = 163 }
            );

            return glucose;
        }

        private NightscoutPebble fetchNightscoutPebbleData(string baseurl, int count = 3)
        {
            var url = $"{baseurl}/pebble?count={count}&units=mgdl";
            var client = new WebClient();

            var contents = client.DownloadString(url);
            return JsonConvert.DeserializeObject<NightscoutPebble>(contents);
        }

        private List<NightscoutApiEntries> fetchNightscoutGlucoseEntries(string baseurl, int count = 3)
        {
            
            var url = $"{baseurl}/api/v1/entries.json?count={count}&units=mgdl&find[sgv][$gt]=0";
            var client = new WebClient();
            Logger.LogInfo($"Calling url {url}");

            var contents = client.DownloadString(url);
            return JsonConvert.DeserializeObject<List<NightscoutApiEntries>>(contents);
        }


        public ActionResult Index(string sessionId, string minutes, string maxCount)
        {
            //the minutes parameter is often 1440 (24 hours), telling you how long back you should do the search
            //In nightscout context it is mostly redundant as the maxCount will search as long back as needed.
            //we ignore that parameter
            Logger.LogInfo("Accesing Glucose Index");
            sessionId = sessionId ?? "";
            int count = int.TryParse(maxCount, out count) ? count : 3;

            if (!this.CheckAuth(sessionId))
            {
                Logger.LogInfo($"Error in checking sessionId");
                return Json("Some error validating sessionid!!", JsonRequestBehavior.AllowGet);
            }

            if (Config.EnableMockedGlucoseMode)
            {
                Logger.LogInfo($"Mocking up glucose value");
                var glucose = mockupGlucoseValues();
                return Content(this.encodeGlucose(glucose), "application/json");
            }


           
            //NightscoutPebble nsglucose = null;
            List<NightscoutApiEntries> nsglucose = null;
            Exception lasterror = null;
            var i = 0;
            do
            {
                var n = i + 1;
                try
                {
                    Logger.LogInfo($"Attempt {n} to fetch glucose from {Config.NsHost}");
                    nsglucose = this.fetchNightscoutGlucoseEntries(Config.NsHost, count);
                    Logger.LogInfo($"Got {nsglucose.Count} entries from nightscout");
                    lasterror=null;
                }
                catch (Exception err)
                {
                    lasterror = err;
                }

            } while (i++ < 2 && lasterror != null );

            if(lasterror != null)
            {
                throw lasterror;
            }
            var shareglucose = new List<ShareGlucose>();

            foreach (var entry in nsglucose)
            {
                var glucosedate = DateTimeOffset.FromUnixTimeMilliseconds(entry.date).DateTime
                                                ;
                decimal val;
                Decimal.TryParse(entry.sgv, out val);

                var trend = SlopeConvert.NsDirectionToShareTrend(entry.direction);

                shareglucose.Add(
                new ShareGlucose
                {
                    DT = glucosedate,
                    ST = glucosedate,
                    WT = glucosedate.ToUniversalTime(),
                    Value = (int)val,
                    Trend = trend
                }

                );
            }

            return Content(this.encodeGlucose(shareglucose), "application/json");
        }
    }
}

NightscoutShareServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using NightscoutShareServer.Utils;
using System.IO;
using System.Globalization;
using System.Web.Hosting;

namespace NightscoutShareServer.Controllers
{
    public class HomeController : Controller
    {
      

        public ActionResult Index()
        {
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            Logger.LogInfo("Accesing Home");
            return View();
        }

        public ActionResult ViewLogs()
        {
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            Logger.LogInfo("Accesing Logs");
            return View("LogsIndex");
        }

        [HttpPost]
        public ActionResult VerifyViewLog(string logsecret)
        {
            if(logsecret != null && logsecret.Length > 11 && Config.DebugViewLogSecret == logsecret) {
                var today = DateTime.Now.ToString("dddd", CultureInfo.InvariantCulture);
                var logfile = Path.Combine(HostingEnvironment.ApplicationPhysicalPath, "Logs",$"{today}.log");

                try
                {
                    ViewBag.logdata = System.IO.File.ReadAllText(logfile);
                    return View("LogsIndex");
                } catch (Exception ex) {
                    return Content($"Could not read log file due to exception: {ex}");
                }
            }
            return View("Error");
        }

        /*
        Example flow from the official site
 Sending json {"accountName":"foo","password":"bar","applicationId":"d89443d2-327c-4a6f-89e5-496bbb0317db"}
 to endpoint https://share1.dexcom.com/ShareWebServices/Services/General/LoginPublisherAccountByName

Response from endpoint https://share1.dexcom.com/ShareWebServices/Services/General/LoginPublisherAccountByName:
"5b4f6f2f-5fc6-4cd7-a921-39ddedd4d24f"

Sending json post null to endpoint
https://share1.dexcom.com/ShareWebServices/Services/Publisher/ReadPublisherLatestGlucoseValues?sessionId=5b4f6f2f-5fc6-4cd7-a921-39ddedd4d24f&minutes=1440&maxCount=3

Response from endpoint
https://share1.dexcom.com/ShareWebServices/Services/Publisher/ReadPublisherLatestGlucoseValues?sessionId=5b4f6f2f-5fc6-4cd7-a921-39ddedd4d24f&minutes=1440&maxCount=3: [{"DT":"\/Date(1489768983000-0700)\/","ST":"\/Date(1489743783000)\/","Trend":4,"Value":104,"WT":"\/Date(1489743778000)\/"},{"DT":"\/Date(1489768442000-0700)\/","ST":"\/Date(1489743242000)\/","Trend":4,"Value":102,"WT":"\/Date(1489743237000)\/"},{"DT":"\/Date(1489768199000-0700)\/","ST":"\/Date(1489742999000)\/","Trend":4,"Value":102,"WT":"\/Date(1489742994000)\/"}]

*/
    }
}

NightscoutShareServer/Views/Home/Index.cshtml
@{
    
    ViewBag.Title = "Home Page";

}

<div>
    <h1>Welcome to NightscoutShareServer</h1>
    <p>This is a custom server that behaves like a Dexcom Share server, but will fetch its glucose values from nightscout</p>
    <p>If you're a nightscout user, you may have heared of the "Dexcom Bridge". This server does the reverse.</p>
    <p>
        By using this custom shareserver, you can use any CGM together with Loop, as long as your cgm data is uploaded to nightscout.
        A consequence is that you don't have to store your glucose data on Dexcom's servers
    </p>

    <h2>Step 0 a): check integration against nightscout</h2>
    <p>
        Please verify that the integration against nightscout is working, click this button
    </p>
    <button id="loadglucose" value="Load Glucose">Load glucose</button>
    <button id="hideglucose" value="Hide glucose" style="visibility:hidden">Hide glucose</button>
    <div id="glucoseinfo">

    </div>
    <h2>Step 0 b): Check Version of Loop. You must be running Loop 1.4.0 or later</h2>
    <p>
        In Loop 1.4.0 there were many changes to make selecting shareserver much easier
    </p>
    
    <h2>Step1: shareserver location</h2>
    <p>
        Take a note of this address: @Request.Url.GetLeftPart(UriPartial.Authority). This is the address to your custom shareserver.
    </p>

    <h2>Step 2: Add cusomt shareserver to Loop</h2>
    <p>
        Open the Loop project directory and navigate to Loop/Models/ServiceAuthentication/ShareService.swift .
        There are comments inside this file describing how to add a new shareserver. Please search the Loop code (cmd+f) for customServer and follow the instructions. Note that customServer variable should be set to the location you wrote down in step 1.

    </p>
   
    <p>
        Recompile the Loop app, and you're all set to go!
        Your customserver should now be build and running, trit it out! It will accept any combination of username and password.
    </p>
</div>

@section Scripts {
    <script>
        var url = "@Url.Action("Index", "Glucose")";
        //nightscoutSite is unused here but included just so you can verify that the environment setting worked
        var nightscoutSite = "@NightscoutShareServer.Utils.Config.NsHost";
        
        var enableMockedMode = "@NightscoutShareServer.Utils.Config.EnableMockedGlucoseMode" === "True";
        var $loadglucose = $("#loadglucose"),
            $glucoseinfo = $("#glucoseinfo"),
            $hideglucose = $("#hideglucose");

        $hideglucose.click(function () {
            $glucoseinfo.find("table").remove();

        });
        Number.prototype.round = function (places) {
            return +(Math.round(this + "e+" + places) + "e-" + places);
        }

        function manipulateResponse(data) {
            for (var key in data) {
                if (data.hasOwnProperty(key)) {
                    var mgdl = data[key].Value;
                    var mmol = (mgdl / 18).round(1);
                    delete data[key].Value;
                    data[key]["Value (mgdl)"] = mgdl;
                    data[key]["Value (mmol)"] = mmol;
                    
                    var wt=new Date(parseInt(data[key].WT.substr(6)));
                    if(!isNaN(wt.getTime())) {
                        data[key]["Locale DateTime"] = wt.toLocaleString();
                    }
                }
            }
            return data;
        }

        $loadglucose.click(function () {
            $.ajax({
                url: url,
                dataType: 'json',
                success: function (data) {
                    $glucoseinfo.find("table").remove();
                    var pretty = prettyPrint(manipulateResponse(data), { maxDepth: 5 })
                    $glucoseinfo.append(pretty);
                    $hideglucose.css("visibility", "visible")
                    enableMockedMode && alert("These data are mocked (don't trust them)!");
                },
                error: function (data, status, error) {
                    alert("Could not retrieve glucose data, please verify your nightscout url:  " + status + ", " + error);
                }
            });
        });
    </script>
}

NightscoutShareServer/Views/Home/LogsIndex.cshtml
@{
    
    ViewBag.Title = "Logs";

}

<div>
    <h1>Logs</h1>
    <p>This is a custom server that behaves like a Dexcom Share server, but will fetch its glucose values from nightscout</p>
    <p>To view todays logs, please define an environment variable (app setting in azure) called Log_Secret and use a value of at least 12 characters</p>
    <p>
       You must match that secret in the form below to be able to view logs
    </p>

   @using (Html.BeginForm("VerifyViewLog", "Home", FormMethod.Post))
{
    <input type="password" name="logsecret" />

    <input type="submit" value="Submit to view logs" />
}

</div>

@if (ViewBag.logdata != null) {
 <h2>logdata</h2>
 <pre>@ViewBag.logdata</pre>
}

@section Scripts {
    <script>
      
    </script>
}